/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaunchAcceptRouteImport } from './routes/launch.accept'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1ReportingSnapshotRouteImport } from './routes/api/v1/reporting/snapshot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchAcceptRoute = LaunchAcceptRouteImport.update({
  id: '/launch/accept',
  path: '/launch/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReportingSnapshotRoute = ApiV1ReportingSnapshotRouteImport.update({
  id: '/api/v1/reporting/snapshot',
  path: '/api/v1/reporting/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/launch/accept': typeof LaunchAcceptRoute
  '/p/$id': typeof PIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/reporting/snapshot': typeof ApiV1ReportingSnapshotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/launch/accept': typeof LaunchAcceptRoute
  '/p/$id': typeof PIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/reporting/snapshot': typeof ApiV1ReportingSnapshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/launch/accept': typeof LaunchAcceptRoute
  '/p/$id': typeof PIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/reporting/snapshot': typeof ApiV1ReportingSnapshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/launch/accept'
    | '/p/$id'
    | '/api/auth/$'
    | '/api/v1/reporting/snapshot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/launch/accept'
    | '/p/$id'
    | '/api/auth/$'
    | '/api/v1/reporting/snapshot'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/launch/accept'
    | '/p/$id'
    | '/api/auth/$'
    | '/api/v1/reporting/snapshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LaunchAcceptRoute: typeof LaunchAcceptRoute
  PIdRoute: typeof PIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1ReportingSnapshotRoute: typeof ApiV1ReportingSnapshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/accept': {
      id: '/launch/accept'
      path: '/launch/accept'
      fullPath: '/launch/accept'
      preLoaderRoute: typeof LaunchAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reporting/snapshot': {
      id: '/api/v1/reporting/snapshot'
      path: '/api/v1/reporting/snapshot'
      fullPath: '/api/v1/reporting/snapshot'
      preLoaderRoute: typeof ApiV1ReportingSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LaunchAcceptRoute: LaunchAcceptRoute,
  PIdRoute: PIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1ReportingSnapshotRoute: ApiV1ReportingSnapshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
